# Generated by Django 6.0.4 on 2026-06-26 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the book was issued')),
                ('due_date', models.DateTimeField(help_text='Date and time when the book should be returned')),
                ('return_date', models.DateTimeField(blank=True, help_text='Date and time when the book was actually returned', null=True)),
                ('status', models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Borrowed', help_text='Current status of the transaction', max_length=20)),
                ('book', models.ForeignKey(help_text='Book that was borrowed', on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to='books.book')),
                ('member', models.ForeignKey(help_text='Member who borrowed the book', on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrow Transaction',
                'verbose_name_plural': 'Borrow Transactions',
                'ordering': ['-issue_date'],
            },
        ),
    ]
