# Generated by Django 6.0.4 on 2026-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fine amount in rupees for late return', max_digits=10),
        ),
    ]
