# Generated by Django 6.0.4 on 2026-06-25 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Librarian', 'Librarian')], default='Member', help_text='User role in the system', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('address', models.TextField(blank=True, help_text='Full address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Profile creation date and time')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
