# Generated by Django 6.0.4 on 2026-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the book title', max_length=200)),
                ('author', models.CharField(help_text='Enter the author name', max_length=100)),
                ('isbn', models.CharField(help_text='13 Character ISBN number', max_length=13, unique=True)),
                ('category', models.CharField(help_text='Enter the book category (e.g., Fiction, Science, History)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the book')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total number of copies in the library')),
                ('available_quantity', models.PositiveIntegerField(default=1, help_text='Number of copies currently available for borrowing')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the book was added to the system')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
